apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-postgres
  template:
    metadata:
      labels:
        app: main-postgres
    spec:
      containers:
      - name: main-postgres
        image: postgres:16
        env:
        - name: POSTGRES_DB
          value: TestDatabase
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
