apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  application.properties: |
    sender-email=vehicletransfer@pms8.com
    spring.mail.host=mailhog-clip
    spring.mail.port=1025
    spring.mail.username=
    spring.mail.password=
    BUYER_NOTIFICATION_URL=http://[INGRESS_HOSTNAME]/login/
    logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
