version: '3.8'
services:
  userAuth:
    image: ghcr.io/billalikakos/userauth:0.92
    ports:
      - "8082:8082"
    networks:
      - keycloak_container_keycloak_demo
networks:
  keycloak_container_keycloak_demo:
    external: true